# fly.toml app configuration file generated for landing-waitlist on 2023-11-27T08:44:06-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "landing-waitlist"
primary_region = "sjc"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
